zbot:
  config:
    main-group-id: 374735267
    main-admin: 875543533
    main-robot-id: 2490390725
    super-admin-list:
      - 875543533
      - 535660742
  service:
    tnoodle: tnoodle.lz1998.xin
    wcads: wcads.lz1998.xin
    vscube: vscube.lz1998.xin
    rank: sunshy.sinaapp.com
    cubing: cubingchina.com
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/zbot?useUnicode=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: localhost
    password: 123456
