spring:
  application:
    name: zbot
  profiles:
    active:
#      - dev
#      - test
      - prod
  bot:
    plugin-list:
      - net.lz1998.zbot.plugin.TestPlugin # 测试
      - net.lz1998.zbot.plugin.JoinGroupPlugin # 新群提示
      - net.lz1998.zbot.plugin.CollisionPlugin # 解决总群冲突
      - net.lz1998.zbot.plugin.LogPlugin # 日志
      - net.lz1998.zbot.plugin.AddFriendPlugin # 自动同意加好友
      - net.lz1998.zbot.plugin.AuthPlugin # 授权
      - net.lz1998.zbot.plugin.BlackPlugin # 黑名单
      - net.lz1998.zbot.plugin.RepeatPlugin # 复读
      - net.lz1998.zbot.plugin.SecurityPlugin # 网页验证码
      - net.lz1998.zbot.plugin.PBlockPlugin # 个人永久屏蔽
      - net.lz1998.zbot.plugin.SwitchPlugin # 开关
      - net.lz1998.zbot.plugin.AdminPlugin # 群管
      - net.lz1998.zbot.plugin.ScramblePlugin # 打乱
      - net.lz1998.zbot.plugin.WcaPlugin # WCA 成绩
      - net.lz1998.zbot.plugin.RankPlugin # WCA 排名
      - net.lz1998.zbot.plugin.LinkPlugin # WCA 粗饼链接
      - net.lz1998.zbot.plugin.TrendPlugin # WCA成绩趋势图
      - net.lz1998.zbot.plugin.SummaryPlugin # 粗饼年度总结
      - net.lz1998.zbot.plugin.CompPlugin # 粗饼赛事查询
      - net.lz1998.zbot.plugin.CuberPlugin # 粗饼比赛选手
      - net.lz1998.zbot.plugin.CubepicPlugin # 生成魔方图
      - net.lz1998.zbot.plugin.WelcomePlugin # 入群欢迎
      - net.lz1998.zbot.plugin.LearnPlugin # 学习 自定义回复内容
      - net.lz1998.zbot.plugin.ExpressPlugin # 快递
      - net.lz1998.zbot.plugin.TranslatePlugin # 翻译
      - net.lz1998.zbot.plugin.SignPlugin # 打卡
      - net.lz1998.zbot.plugin.NsfwPlugin # nsfw
    event:
      max-pool-size: 300
      core-pool-size: 20
      work-queue-size: 10240
      keep-alive-time: 2000
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}
