spring:
  profiles:
    active: dev
  bot:
    plugin-list:
      - net.lz1998.zbot.plugin.TestPlugin
      - net.lz1998.zbot.plugin.CollisionPlugin
      - net.lz1998.zbot.plugin.LogPlugin
      - net.lz1998.zbot.plugin.AddFriendPlugin
      - net.lz1998.zbot.plugin.RepeatPlugin
      - net.lz1998.zbot.plugin.SwitchPlugin
      - net.lz1998.zbot.plugin.ScramblePlugin